import 'package:flutter/material.dart';
import 'package:get/get.dart';

class LanguagePicker extends Translations {
  @override
  Map<String, Map<String, String>> get keys => {
        // Portuguese translation - native language
        'pt_BR': {
          "text1": "Portugûes",
          "text2": "English",
          "text3": "Español",
          "text4": "Mais...",
          "text5": "Telefone ou email",
          "text6": "Senha",
          "text7": "Esqueceu a",
          "text8": "senha?",
          "text9": "OU",
          "text10": "Encontrar sua conta",
          "text11": "Insira seu telefone",
          "text12": "Telefone",
          "text13": "Insira seu email",
          "text14": "Email",
          "text15": "Criar conta",
          "text16": "Participe do Facebook",
          "text17": "Ajudaremos você a criar uma nova conta em",
          "text18": "alguma etapas simples.",
          "text19": "Deseja interromper a criação da sua conta?",
          "text20": "Se você parar agora, perderá todo o processo feito.",
          "button1": "Entrar",
          "button2": "Criar nova conta do Facebook",
          "button3": "Pesquisar pelo seu email",
          "button4": "Pesquisar pelo seu telefone",
          "button5": "Avançar",
          "button6": "Já tem uma conta?",
          "button7": "Continuar a criar a conta",
          "button8": "Parar de criar a conta",
        },
        // English translation
        'en_US': {
          "text1": "Portugûes",
          "text2": "English",
          "text3": "Español",
          "text4": "More...",
          "text5": "Phone or email",
          "text6": "Password",
          "text7": "Forgot Password?",
          "text8": "",
          "text9": "OR",
          "text10": "Find your account",
          "text11": "Enter Your Phone Number",
          "text12": "Phone",
          "text13": "Enter Your Email",
          "text14": "Email",
          "text15": "Create account",
          "text16": "Join Facebook",
          "text17": "We'll help you create a new account in a few easy",
          "text18": "steps.",
          "text19": "Do you want to stop creating your account?",
          "text20": "If you stop now, you'll lose any progress you've made.",
          "button1": "Log In",
          "button2": "Create new Facebook account",
          "button3": "Search by your email instead",
          "button4": "Search by your phone instead",
          "button5": "Next",
          "button6": "Already have an account",
          "button7": "Continue creating account",
          "button8": "Stop creating account",
        },
        // Espanish translation
        'es_ES': {
          "text1": "Portugûes",
          "text2": "English",
          "text3": "Español",
          "text4": "Más...",
          "text5": "Teléfono o correo electrónico",
          "text6": "Contraseña",
          "text7": "¿Olvidaste tu",
          "text8": "contraseña?",
          "text9": "O",
          "text10": "Buscar tu cuenta",
          "text11": "Ingresa tu número de teléfono",
          "text12": "Teléfono",
          "text13": "Ingresa tu correo electrónico",
          "text14": "Correo electrónico",
          "text15": "Crear cuenta",
          "text16": "Únete a Facebook",
          "text17": "Te ayudaremos a crear una cuenta en pocos pasos.",
          "text18": "",
          "text19": "¿Quieres salir sin terminar de crear la cuenta?",
          "text20": "Si sales ahora, perderás el progreso que hayas hecho.",
          "button1": "Iniciar sesión",
          "button2": "Crear cuenta de Facebook",
          "button3": "Buscar por tu correo electrónico",
          "button4": "Buscar por tu teléfono",
          "button5": "Siguiente",
          "button6": "¿Ya tienes una cuenta?",
          "button7": "Seguir cureando la cuenta",
          "button8": "Salir sin crearla cuenta",
        }
      };
}
